PYTHON = "python"
JAVA = "java"
FASTAPI = "fastapi"
BCRYPT = "bcrypt"

SPRING_BOOT = "spring-boot"
PYPI = "Pypi"
GITHUB = "github"
MAVEN = "Maven"
SPRING_SECURITY ="org.springframework.security:spring-security-core"